name: github packages

on:
  push:
    branches:
      - "master"
    paths:
      - "Dockerfile"
  pull_request:
    paths:
      - "Dockerfile"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository }}/gtk4
          tags: latest
